
import 'package:flutter_pdfmaker/textform.dart';
import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';


class DBProvider {
  static Database database;

  static Future<void> setDb() async{
    if(database == null) {
      database = await initDb();
      return database;
    }
    else {
      return database;
    }
  }

  static Map<int, String> createTableList = {
    2 : "CREATE TABLE file(id INTEGER PRIMARY KEY AUTOINCREMENT,head TEXT,firstDate TEXT,belongs TEXT,groupName TEXT,represent TEXT,firstAddress1 TEXT,firstAddress2 TEXT,firstAddress3 TEXT,firstAddress4 TEXT,firstTel TEXT,emergeName TEXT,emergeTel TEXT,emergeAddress1 TEXT,emergeAddress2 TEXT,emergeAddress3 TEXT,emergeAddress4 TEXT,localPoint1 TEXT,localPoint2 TEXT,localPoint3 TEXT,localTel1 TEXT,localTel2 TEXT,localTel3 TEXT,id1Role TEXT,id1Name TEXT,id1NameH TEXT,id1Sex TEXT,id1Age TEXT,id1Birth TEXT,id1Blood TEXT,id1Address1 TEXT,id1Address2 TEXT,id1Address3 TEXT,id1Address4 TEXT,id1HouseTel TEXT,id1SelTel TEXT,id1EmergeName TEXT,id1EmergeTel TEXT,id2Role TEXT,id2Name TEXT,id2NameH TEXT,id2Sex TEXT,id2Age TEXT,id2Birth TEXT,id2Blood TEXT,id2Address1 TEXT,id2Address2 TEXT,id2Address3 TEXT,id2Address4 TEXT,id2HouseTel TEXT,id2SelTel TEXT,id2EmergeName TEXT,id2EmergeTel TEXT,id3Role TEXT,id3Name TEXT,id3NameH TEXT,id3Sex TEXT,id3Age TEXT,id3Birth TEXT,id3Blood TEXT,id3Address1 TEXT,id3Address2 TEXT,id3Address3 TEXT,id3Address4 TEXT,id3HouseTel TEXT,id3SelTel TEXT,id3EmergeName TEXT,id3EmergeTel TEXT,id4Role TEXT,id4Name TEXT,id4NameH TEXT,id4Sex TEXT,id4Age TEXT,id4Birth TEXT,id4Blood TEXT,id4Address1 TEXT,id4Address2 TEXT,id4Address3 TEXT,id4Address4 TEXT,id4HouseTel TEXT,id4SelTel TEXT,id4EmergeName TEXT,id4EmergeTel TEXT,id5Role TEXT,id5Name TEXT,id5NameH TEXT,id5Sex TEXT,id5Age TEXT,id5Birth TEXT,id5Blood TEXT,id5Address1 TEXT,id5Address2 TEXT,id5Address3 TEXT,id5Address4 TEXT,id5HouseTel TEXT,id5SelTel TEXT,id5EmergeName TEXT,id5EmergeTel TEXT,destination TEXT,method TEXT,start TEXT,sTime TEXT,finish TEXT,fTime TEXT,date1 TEXT,date2 TEXT,date3 TEXT,date4 TEXT,date5 TEXT,date6 TEXT,action1 TEXT,action2 TEXT,action3 TEXT,action4 TEXT,action5 TEXT,action6 TEXT,other1 TEXT,other2 TEXT,other3 TEXT,zack BOOLEAN,shoes BOOLEAN,rainWear BOOLEAN,sleepBag BOOLEAN,headLmp BOOLEAN,light BOOLEAN,battery BOOLEAN,compass BOOLEAN,planDoc BOOLEAN,selPhone BOOLEAN,lighter BOOLEAN,zackCover BOOLEAN,sleepBagCover BOOLEAN,helmet BOOLEAN,crampons BOOLEAN,iceAx BOOLEAN,snack BOOLEAN,mask BOOLEAN,alMeter BOOLEAN,tissue BOOLEAN,map BOOLEAN,winterClothes BOOLEAN,medicalCase BOOLEAN,towel BOOLEAN,stick BOOLEAN,knife BOOLEAN,thermometer BOOLEAN,changeClothes BOOLEAN,gloves BOOLEAN,workGloves BOOLEAN,cap BOOLEAN,rainSpats BOOLEAN,insects BOOLEAN,copy BOOLEAN,food BOOLEAN,num1 TEXT,subFood BOOLEAN,num2 TEXT,emergeFood BOOLEAN,cal TEXT,water BOOLEAN,amount TEXT,perOther TEXT,tent BOOLEAN,hob BOOLEAN,gas BOOLEAN,subGas BOOLEAN,rope BOOLEAN,celtic BOOLEAN,mat BOOLEAN,cup BOOLEAN,cook BOOLEAN,joinOther TEXT,title TEXT,date TEXT,path TEXT)"
  };

  static Future<Database> initDb() async{
    String path = join(await getDatabasesPath(), "a.db");
    return await openDatabase(
      path,
      version: 1,
      onCreate: _createTable,
      onUpgrade: (Database db, int oldVersion, int newVersion) async{
        for(int i = oldVersion + 1; i <= newVersion; i++) {
          var query = createTableList[i];
          await db.execute(query);
        }
      },
    );
  }


  static Future<void> _createTable(Database db, int version) async {
    for(int i=2; i<=2;i++) {
      var query = createTableList[i];
      await db.execute(query);
    }
  }


  static Future<List<AllData>> getFileData() async{
    final List<Map<String, dynamic>> maps = await database.query('file');
    return List.generate(maps.length, (i){
      return AllData(
        id: maps[i]['id'],
        head: maps[i]['head'],
        firstDate: maps[i]['firstData'],
        belongs: maps[i]['belongs'],
        groupName: maps[i]['groupName'],
        represent: maps[i]['represent'],
        firstAddress1: maps[i]['firstAddress1'],
        firstAddress2: maps[i]['firstAddress2'],
        firstAddress3: maps[i]['firstAddress3'],
        firstAddress4: maps[i]['firstAddress4'],
        firstTel: maps[i]['firstTel'],
        emergeName: maps[i]['emergeName'],
        emergeTel: maps[i]['emergeTel'],
        emergeAddress1: maps[i]['emergeAddress1'],
        emergeAddress2: maps[i]['emergeAddress2'],
        emergeAddress3: maps[i]['emergeAddress3'],
        emergeAddress4: maps[i]['emergeAddress4'],
        localPoint1: maps[i]['localPoint1'],
        localPoint2: maps[i]['localPoint2'],
        localPoint3: maps[i]['localPoint3'],
        localTel1: maps[i]['localTel1'],
        localTel2: maps[i]['localTel2'],
        localTel3: maps[i]['localTel3'],
        id1Role: maps[i]['id1Role'],
        id1Name: maps[i]['id1Name'],
        id1NameH: maps[i]['id1NameH'],
        id1Sex: maps[i]['id1Sex'],
        id1Age: maps[i]['id1Age'],
        id1Birth: maps[i]['id1Birth'],
        id1Blood: maps[i]['id1Blood'],
        id1Address1: maps[i]['id1Address1'],
        id1Address2: maps[i]['id1Address2'],
        id1Address3: maps[i]['id1Address3'],
        id1Address4: maps[i]['id1Address4'],
        id1HouseTel: maps[i]['id1HouseTel'],
        id1SelTel: maps[i]['id1SelTel'],
        id1EmergeName: maps[i]['id1EmergeName'],
        id1EmergeTel: maps[i]['id1EmergeTel'],
        id2Role: maps[i]['id2Role'],
        id2Name: maps[i]['id2Name'],
        id2NameH: maps[i]['id2NameH'],
        id2Sex: maps[i]['id2Sex'],
        id2Age: maps[i]['id2Age'],
        id2Birth: maps[i]['id2Birth'],
        id2Blood: maps[i]['id2Blood'],
        id2Address1: maps[i]['id2Address1'],
        id2Address2: maps[i]['id2Address2'],
        id2Address3: maps[i]['id2Address3'],
        id2Address4: maps[i]['id2Address4'],
        id2HouseTel: maps[i]['id2HouseTel'],
        id2SelTel: maps[i]['id2SelTel'],
        id2EmergeName: maps[i]['id2EmergeName'],
        id2EmergeTel: maps[i]['id2EmergeTel'],
        id3Role: maps[i]['id3Role'],
        id3Name: maps[i]['id3Name'],
        id3NameH: maps[i]['id3NameH'],
        id3Sex: maps[i]['id3Sex'],
        id3Age: maps[i]['id3Age'],
        id3Birth: maps[i]['id3Birth'],
        id3Blood: maps[i]['id3Blood'],
        id3Address1: maps[i]['id3Address1'],
        id3Address2: maps[i]['id3Address2'],
        id3Address3: maps[i]['id3Address3'],
        id3Address4: maps[i]['id3Address4'],
        id3HouseTel: maps[i]['id3HouseTel'],
        id3SelTel: maps[i]['id3SelTel'],
        id3EmergeName: maps[i]['id3EmergeName'],
        id3EmergeTel: maps[i]['id3EmergeTel'],
        id4Role: maps[i]['id4Role'],
        id4Name: maps[i]['id4Name'],
        id4NameH: maps[i]['id4NameH'],
        id4Sex: maps[i]['id4Sex'],
        id4Age: maps[i]['id4Age'],
        id4Birth: maps[i]['id4Birth'],
        id4Blood: maps[i]['id4Blood'],
        id4Address1: maps[i]['id4Address1'],
        id4Address2: maps[i]['id4Address2'],
        id4Address3: maps[i]['id4Address3'],
        id4Address4: maps[i]['id4Address4'],
        id4HouseTel: maps[i]['id4HouseTel'],
        id4SelTel: maps[i]['id4SelTel'],
        id4EmergeName: maps[i]['id4EmergeName'],
        id4EmergeTel: maps[i]['id4EmergeTel'],
        id5Role: maps[i]['id5Role'],
        id5Name: maps[i]['id5Name'],
        id5NameH: maps[i]['id5NameH'],
        id5Sex: maps[i]['id5Sex'],
        id5Age: maps[i]['id5Age'],
        id5Birth: maps[i]['id5Birth'],
        id5Blood: maps[i]['id5Blood'],
        id5Address1: maps[i]['id5Address1'],
        id5Address2: maps[i]['id5Address2'],
        id5Address3: maps[i]['id5Address3'],
        id5Address4: maps[i]['id5Address4'],
        id5HouseTel: maps[i]['id5HouseTel'],
        id5SelTel: maps[i]['id5SelTel'],
        id5EmergeName: maps[i]['id5EmergeName'],
        id5EmergeTel: maps[i]['id5EmergeTel'],
        destination: maps[i]['destination'],
        method: maps[i]['method'],
        start: maps[i]['start'],
        sTime: maps[i]['sTime'],
        finish: maps[i]['finish'],
        fTime: maps[i]['fTime'],
        date2: maps[i]['date1d'],
        date3: maps[i]['date3'],
        date4: maps[i]['date4'],
        date5: maps[i]['date5'],
        date6: maps[i]['date6'],
        action1: maps[i]['action1'],
        action2: maps[i]['action2'],
        action3: maps[i]['action3'],
        action4: maps[i]['action4'],
        action5: maps[i]['action5'],
        action6: maps[i]['action6'],
        other1: maps[i]['other1'],
        zack: maps[i]['zack'] == 1,
        shoes: maps[i]['shoes'] == 1,
        rainWear: maps[i]['rainWear'] == 1,
        sleepBag: maps[i]['sleepBag'] == 1,
        headLmp: maps[i]['headLmp'] == 1,
        light: maps[i]['light'] == 1,
        battery: maps[i]['battery'] == 1,
        compass: maps[i]['compass'] == 1,
        planDoc: maps[i]['planDoc'] == 1,
        selPhone: maps[i]['selPhone'] == 1,
        lighter: maps[i]['lighter'] == 1,
        zackCover: maps[i]['zackCover'] == 1,
        sleepBagCover: maps[i]['sleepBagCover'] == 1,
        helmet: maps[i]['helmet'] == 1,
        crampons: maps[i]['crampons'] == 1,
        iceAx: maps[i]['iceAx'] == 1,
        snack: maps[i]['snack'] == 1,
        mask: maps[i]['mask'] == 1,
        alMeter: maps[i]['alMeter'] == 1,
        tissue: maps[i]['tissue'] == 1,
        map: maps[i]['map'] == 1,
        winterClothes: maps[i]['winterClothes'] == 1,
        medicalCase: maps[i]['medicalCase'] == 1,
        towel: maps[i]['towel'] == 1,
        stick: maps[i]['stick'] == 1,
        knife: maps[i]['knife'] == 1,
        thermometer: maps[i]['thermometer'] == 1,
        changeClothes: maps[i]['changeClothes'] == 1,
        gloves: maps[i]['gloves'] == 1,
        workGloves: maps[i]['workGloves'] == 1,
        cap: maps[i]['cap'] == 1,
        rainSpats: maps[i]['rainSpats'] == 1,
        insects: maps[i]['insects'] == 1,
        copy: maps[i]['copy'] == 1,
        food: maps[i]['food'] == 1,
        num1: maps[i]['num1'],
        subFood: maps[i]['subFood'] == 1,
        num2: maps[i]['num2'],
        emergeFood: maps[i]['emergeFood'] == 1,
        cal: maps[i]['cal'],
        water: maps[i]['water'] == 1,
        amount: maps[i]['amount'],
        perOther: maps[i]['perOther'],
        tent: maps[i]['tent'] == 1,
        hob: maps[i]['hob'] == 1,
        gas: maps[i]['gas'] == 1,
        subGas: maps[i]['subGas'] == 1,
        rope: maps[i]['rope'] == 1,
        celtic: maps[i]['celtic'] == 1,
        mat: maps[i]['mat'] == 1,
        cup: maps[i]['cup'] == 1,
        cook: maps[i]['cook'] == 1,
        joinOther: maps[i]['joinOther'],
        file: maps[i]['title'],
        date: maps[i]['date'],
        path: maps[i]['path'],
      );
    });
  }

  static Future<void> insertFileData(AllData saveData) async{
    await database.insert(
        'file',
        {
          'head':saveData.head,
          'firstDate':saveData.firstDate,
          'belongs':saveData.belongs,
          'groupName':saveData.groupName,
          'represent':saveData.represent,
          'firstAddress1':saveData.firstAddress1,
          'firstAddress2':saveData.firstAddress2,
          'firstAddress3':saveData.firstAddress3,
          'firstAddress4':saveData.firstAddress4,
          'firstTel':saveData.firstTel,
          'emergeName':saveData.emergeName,
          'emergeTel':saveData.emergeTel,
          'emergeAddress1':saveData.emergeAddress1,
          'emergeAddress2':saveData.emergeAddress2,
          'emergeAddress3':saveData.emergeAddress3,
          'emergeAddress4':saveData.emergeAddress4,
          'localPoint1':saveData.localPoint1,
          'localPoint2':saveData.localPoint2,
          'localPoint3':saveData.localPoint3,
          'localTel1':saveData.localTel1,
          'localTel2':saveData.localTel2,
          'localTel3':saveData.localTel3,
          'id1Role':saveData.id1Role,
          'id1Name':saveData.id1Name,
          'id1NameH':saveData.id1NameH,
          'id1Sex':saveData.id1Sex,
          'id1Age':saveData.id1Age,
          'id1Birth':saveData.id1Birth,
          'id1Blood':saveData.id1Blood,
          'id1Address1':saveData.id1Address1,
          'id1Address2':saveData.id1Address2,
          'id1Address3':saveData.id1Address3,
          'id1Address4':saveData.id1Address4,
          'id1HouseTel':saveData.id1HouseTel,
          'id1SelTel':saveData.id1SelTel,
          'id1EmergeName':saveData.id1EmergeName,
          'id1EmergeTel':saveData.id1EmergeTel,
          'id2Role':saveData.id2Role,
          'id2Name':saveData.id2Name,
          'id2NameH':saveData.id2NameH,
          'id2Sex':saveData.id2Sex,
          'id2Age':saveData.id2Age,
          'id2Birth':saveData.id2Birth,
          'id2Blood':saveData.id2Blood,
          'id2Address1':saveData.id2Address1,
          'id2Address2':saveData.id2Address2,
          'id2Address3':saveData.id2Address3,
          'id2Address4':saveData.id2Address4,
          'id2HouseTel':saveData.id2HouseTel,
          'id2SelTel':saveData.id2SelTel,
          'id2EmergeName':saveData.id2EmergeName,
          'id2EmergeTel':saveData.id2EmergeTel,
          'id3Role':saveData.id3Role,
          'id3Name':saveData.id3Name,
          'id3NameH':saveData.id3NameH,
          'id3Sex':saveData.id3Sex,
          'id3Age':saveData.id3Age,
          'id3Birth':saveData.id3Birth,
          'id3Blood':saveData.id3Blood,
          'id3Address1':saveData.id3Address1,
          'id3Address2':saveData.id3Address2,
          'id3Address3':saveData.id3Address3,
          'id3Address4':saveData.id3Address4,
          'id3HouseTel':saveData.id3HouseTel,
          'id3SelTel':saveData.id3SelTel,
          'id3EmergeName':saveData.id3EmergeName,
          'id3EmergeTel':saveData.id3EmergeTel,
          'id4Role':saveData.id4Role,
          'id4Name':saveData.id4Name,
          'id4NameH':saveData.id4NameH,
          'id4Sex':saveData.id4Sex,
          'id4Age':saveData.id4Age,
          'id4Birth':saveData.id4Birth,
          'id4Blood':saveData.id4Blood,
          'id4Address1':saveData.id4Address1,
          'id4Address2':saveData.id4Address2,
          'id4Address3':saveData.id4Address3,
          'id4Address4':saveData.id4Address4,
          'id4HouseTel':saveData.id4HouseTel,
          'id4SelTel':saveData.id4SelTel,
          'id4EmergeName':saveData.id4EmergeName,
          'id4EmergeTel':saveData.id4EmergeTel,
          'id5Role':saveData.id5Role,
          'id5Name':saveData.id5Name,
          'id5NameH':saveData.id5NameH,
          'id5Sex':saveData.id5Sex,
          'id5Age':saveData.id5Age,
          'id5Birth':saveData.id5Birth,
          'id5Blood':saveData.id5Blood,
          'id5Address1':saveData.id5Address1,
          'id5Address2':saveData.id5Address2,
          'id5Address3':saveData.id5Address3,
          'id5Address4':saveData.id5Address4,
          'id5HouseTel':saveData.id5HouseTel,
          'id5SelTel':saveData.id5SelTel,
          'id5EmergeName':saveData.id5EmergeName,
          'id5EmergeTel':saveData.id5EmergeTel,
          'destination':saveData.destination,
          'method':saveData.method,
          'start':saveData.start,
          'sTime':saveData.sTime,
          'finish':saveData.finish,
          'fTime':saveData.sTime,
          'date1':saveData.date1,
          'date2':saveData.date2,
          'date3':saveData.date3,
          'date4':saveData.date4,
          'date5':saveData.date5,
          'date6':saveData.date6,
          'action1':saveData.action1,
          'action2':saveData.action2,
          'action3':saveData.action3,
          'action4':saveData.action4,
          'action5':saveData.action5,
          'action6':saveData.action6,
          'other1':saveData.other1,
          'zack':saveData.zack ? 1 : 0,
          'shoes':saveData.shoes ? 1 : 0,
          'rainWear':saveData.rainWear ? 1 : 0,
          'sleepBag':saveData.sleepBag ? 1 : 0,
          'headLmp':saveData.headLmp ? 1 : 0,
          'light':saveData.light ? 1 : 0,
          'battery':saveData.battery ? 1 : 0,
          'compass':saveData.compass ? 1 : 0,
          'planDoc':saveData.planDoc ? 1 : 0,
          'selPhone':saveData.selPhone ? 1 : 0,
          'lighter':saveData.lighter ? 1 : 0,
          'zackCover':saveData.zackCover ? 1 : 0,
          'sleepBagCover':saveData.sleepBagCover ? 1 : 0,
          'helmet':saveData.helmet ? 1 : 0,
          'crampons':saveData.crampons ? 1 : 0,
          'iceAx':saveData.iceAx ? 1 : 0,
          'snack':saveData.snack ? 1 : 0,
          'mask':saveData.mask ? 1 : 0,
          'alMeter':saveData.alMeter ? 1 : 0,
          'tissue':saveData.tissue ? 1 : 0,
          'map':saveData.map ? 1 : 0,
          'winterClothes':saveData.winterClothes ? 1 : 0,
          'medicalCase':saveData.medicalCase ? 1 : 0,
          'towel':saveData.towel ? 1 : 0,
          'stick':saveData.stick ? 1 : 0,
          'knife':saveData.knife ? 1 : 0,
          'thermometer':saveData.thermometer ? 1 : 0,
          'changeClothes':saveData.changeClothes ? 1 : 0,
          'gloves':saveData.gloves ? 1 : 0,
          'workGloves':saveData.workGloves ? 1 : 0,
          'cap':saveData.cap ? 1 : 0,
          'rainSpats':saveData.rainSpats ? 1 : 0,
          'insects':saveData.insects ? 1 : 0,
          'copy':saveData.copy ? 1 : 0,
          'food':saveData.food ? 1 : 0,
          'num1':saveData.num1,
          'subFood':saveData.subFood ? 1 : 0,
          'num2':saveData.num2,
          'emergeFood':saveData.emergeFood ? 1 : 0,
          'cal':saveData.cal,
          'water':saveData.water ? 1 : 0,
          'amount':saveData.amount,
          'perOther':saveData.perOther,
          'tent':saveData.tent ? 1 : 0,
          'hob':saveData.hob ? 1 : 0,
          'gas':saveData.gas ? 1 : 0,
          'subGas':saveData.subGas ? 1 : 0,
          'rope':saveData.rope ? 1 : 0,
          'celtic':saveData.celtic ? 1 : 0,
          'mat':saveData.mat ? 1 : 0,
          'cup':saveData.cup ? 1 : 0,
          'cook':saveData.cook ? 1 : 0,
          'joinOther':saveData.joinOther,
          'title':saveData.file,
          'date':saveData.date,
          'path':saveData.path,

        }
    );
  }

  static Future<void> updateFileData(AllData saveData, int index) async {
    await database.update(
      'file',
      {
        'head':saveData.head,
        'firstDate':saveData.firstDate,
        'belongs':saveData.belongs,
        'groupName':saveData.groupName,
        'represent':saveData.represent,
        'firstAddress1':saveData.firstAddress1,
        'firstAddress2':saveData.firstAddress2,
        'firstAddress3':saveData.firstAddress3,
        'firstAddress4':saveData.firstAddress4,
        'firstTel':saveData.firstTel,
        'emergeName':saveData.emergeName,
        'emergeTel':saveData.emergeTel,
        'emergeAddress1':saveData.emergeAddress1,
        'emergeAddress2':saveData.emergeAddress2,
        'emergeAddress3':saveData.emergeAddress3,
        'emergeAddress4':saveData.emergeAddress4,
        'localPoint1':saveData.localPoint1,
        'localPoint2':saveData.localPoint2,
        'localPoint3':saveData.localPoint3,
        'localTel1':saveData.localTel1,
        'localTel2':saveData.localTel2,
        'localTel3':saveData.localTel3,
        'id1Role':saveData.id1Role,
        'id1Name':saveData.id1Name,
        'id1NameH':saveData.id1NameH,
        'id1Sex':saveData.id1Sex,
        'id1Age':saveData.id1Age,
        'id1Birth':saveData.id1Birth,
        'id1Blood':saveData.id1Blood,
        'id1Address1':saveData.id1Address1,
        'id1Address2':saveData.id1Address2,
        'id1Address3':saveData.id1Address3,
        'id1Address4':saveData.id1Address4,
        'id1HouseTel':saveData.id1HouseTel,
        'id1SelTel':saveData.id1SelTel,
        'id1EmergeName':saveData.id1EmergeName,
        'id1EmergeTel':saveData.id1EmergeTel,
        'id2Role':saveData.id2Role,
        'id2Name':saveData.id2Name,
        'id2NameH':saveData.id2NameH,
        'id2Sex':saveData.id2Sex,
        'id2Age':saveData.id2Age,
        'id2Birth':saveData.id2Birth,
        'id2Blood':saveData.id2Blood,
        'id2Address1':saveData.id2Address1,
        'id2Address2':saveData.id2Address2,
        'id2Address3':saveData.id2Address3,
        'id2Address4':saveData.id2Address4,
        'id2HouseTel':saveData.id2HouseTel,
        'id2SelTel':saveData.id2SelTel,
        'id2EmergeName':saveData.id2EmergeName,
        'id2EmergeTel':saveData.id2EmergeTel,
        'id3Role':saveData.id3Role,
        'id3Name':saveData.id3Name,
        'id3NameH':saveData.id3NameH,
        'id3Sex':saveData.id3Sex,
        'id3Age':saveData.id3Age,
        'id3Birth':saveData.id3Birth,
        'id3Blood':saveData.id3Blood,
        'id3Address1':saveData.id3Address1,
        'id3Address2':saveData.id3Address2,
        'id3Address3':saveData.id3Address3,
        'id3Address4':saveData.id3Address4,
        'id3HouseTel':saveData.id3HouseTel,
        'id3SelTel':saveData.id3SelTel,
        'id3EmergeName':saveData.id3EmergeName,
        'id3EmergeTel':saveData.id3EmergeTel,
        'id4Role':saveData.id4Role,
        'id4Name':saveData.id4Name,
        'id4NameH':saveData.id4NameH,
        'id4Sex':saveData.id4Sex,
        'id4Age':saveData.id4Age,
        'id4Birth':saveData.id4Birth,
        'id4Blood':saveData.id4Blood,
        'id4Address1':saveData.id4Address1,
        'id4Address2':saveData.id4Address2,
        'id4Address3':saveData.id4Address3,
        'id4Address4':saveData.id4Address4,
        'id4HouseTel':saveData.id4HouseTel,
        'id4SelTel':saveData.id4SelTel,
        'id4EmergeName':saveData.id4EmergeName,
        'id4EmergeTel':saveData.id4EmergeTel,
        'id5Role':saveData.id5Role,
        'id5Name':saveData.id5Name,
        'id5NameH':saveData.id5NameH,
        'id5Sex':saveData.id5Sex,
        'id5Age':saveData.id5Age,
        'id5Birth':saveData.id5Birth,
        'id5Blood':saveData.id5Blood,
        'id5Address1':saveData.id5Address1,
        'id5Address2':saveData.id5Address2,
        'id5Address3':saveData.id5Address3,
        'id5Address4':saveData.id5Address4,
        'id5HouseTel':saveData.id5HouseTel,
        'id5SelTel':saveData.id5SelTel,
        'id5EmergeName':saveData.id5EmergeName,
        'id5EmergeTel':saveData.id5EmergeTel,
        'destination':saveData.destination,
        'method':saveData.method,
        'start':saveData.start,
        'sTime':saveData.sTime,
        'finish':saveData.finish,
        'fTime':saveData.sTime,
        'date1':saveData.date1,
        'date2':saveData.date2,
        'date3':saveData.date3,
        'date4':saveData.date4,
        'date5':saveData.date5,
        'date6':saveData.date6,
        'action1':saveData.action1,
        'action2':saveData.action2,
        'action3':saveData.action3,
        'action4':saveData.action4,
        'action5':saveData.action5,
        'action6':saveData.action6,
        'other1':saveData.other1,
        'zack':saveData.zack ? 1 : 0,
        'shoes':saveData.shoes ? 1 : 0,
        'rainWear':saveData.rainWear ? 1 : 0,
        'sleepBag':saveData.sleepBag ? 1 : 0,
        'headLmp':saveData.headLmp ? 1 : 0,
        'light':saveData.light ? 1 : 0,
        'battery':saveData.battery ? 1 : 0,
        'compass':saveData.compass ? 1 : 0,
        'planDoc':saveData.planDoc ? 1 : 0,
        'selPhone':saveData.selPhone ? 1 : 0,
        'lighter':saveData.lighter ? 1 : 0,
        'zackCover':saveData.zackCover ? 1 : 0,
        'sleepBagCover':saveData.sleepBagCover ? 1 : 0,
        'helmet':saveData.helmet ? 1 : 0,
        'crampons':saveData.crampons ? 1 : 0,
        'iceAx':saveData.iceAx ? 1 : 0,
        'snack':saveData.snack ? 1 : 0,
        'mask':saveData.mask ? 1 : 0,
        'alMeter':saveData.alMeter ? 1 : 0,
        'tissue':saveData.tissue ? 1 : 0,
        'map':saveData.map ? 1 : 0,
        'winterClothes':saveData.winterClothes ? 1 : 0,
        'medicalCase':saveData.medicalCase ? 1 : 0,
        'towel':saveData.towel ? 1 : 0,
        'stick':saveData.stick ? 1 : 0,
        'knife':saveData.knife ? 1 : 0,
        'thermometer':saveData.thermometer ? 1 : 0,
        'changeClothes':saveData.changeClothes ? 1 : 0,
        'gloves':saveData.gloves ? 1 : 0,
        'workGloves':saveData.workGloves ? 1 : 0,
        'cap':saveData.cap ? 1 : 0,
        'rainSpats':saveData.rainSpats ? 1 : 0,
        'insects':saveData.insects ? 1 : 0,
        'copy':saveData.copy ? 1 : 0,
        'food':saveData.food ? 1 : 0,
        'num1':saveData.num1,
        'subFood':saveData.subFood ? 1 : 0,
        'num2':saveData.num2,
        'emergeFood':saveData.emergeFood ? 1 : 0,
        'cal':saveData.cal,
        'water':saveData.water ? 1 : 0,
        'amount':saveData.amount,
        'perOther':saveData.perOther,
        'tent':saveData.tent ? 1 : 0,
        'hob':saveData.hob ? 1 : 0,
        'gas':saveData.gas ? 1 : 0,
        'subGas':saveData.subGas ? 1 : 0,
        'rope':saveData.rope ? 1 : 0,
        'celtic':saveData.celtic ? 1 : 0,
        'mat':saveData.mat ? 1 : 0,
        'cup':saveData.cup ? 1 : 0,
        'cook':saveData.cook ? 1 : 0,
        'joinOther':saveData.joinOther,
        'title':saveData.file,
        'date':saveData.date,
        'path':saveData.path,
      },
      where: "id = ?",
      whereArgs: [index],
      conflictAlgorithm: ConflictAlgorithm.fail,
    );
  }

  static Future<void> deleteFileData(int index) async {
    await database.delete(
      'file',
      where: "id = ?",
      whereArgs: [index],
    );
  }


  static Future<void> deleteDB() async {
    await database.delete('file');
  }
}


